config/routes.rb
Rails.application.routes.draw do
  resources :users do
    resources :cars, controller: :catagories, type: 'Car'
    resources :motorcycles, controller: :catagories, type: 'Motorcycle'
  end
  root to: 'users#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < Catagory
  belongs_to :user
end

app/models/catagory.rb
class Catagory < ApplicationRecord
  
    scope :cars, -> { where(type: 'Car') } 
  scope :motorcycles, -> { where(type: 'Motorcycle') }
end

app/models/motorcycle.rb
class Motorcycle < Catagory
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    has_many :cars, class_name: 'Car'
  has_many :motorcycles, class_name: 'Motorcycle'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
end

app/controllers/catagories_controller.rb
class CatagoriesController < ApplicationController
    #before_action :set_catagory, only: [:show, :edit, :update, :destroy]

  def new
    @user = User.find(params[:user_id])
    @catagory = @user.send(set_type.pluralize).new 
  end

  def edit
  end

  def create
    @user = User.find(params[:user_id])
    @catagory = @user.send(set_type.pluralize).new(catagory_params)
    if @catagory.save
      redirect_to @user
    else
      render :new
    end
  end

  def update
    if @catagory.update(catagory_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @catagory.destroy
    redirect_to @user
  end

  private
    def set_catagory
      @user = User.find(params[:user_id])
      @catagory = @user.send(set_type.pluralize).find(params[:id]) 
    end

    def set_type
      case params[:type]
      when 'Car'
        'car'
      when 'Motorcycle'
        'motorcycle'
      end
    end

    def catagory_params
      params.require(set_type.to_sym).permit(:type, :price, :color, :model, :company, :city, :address)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :set_user, only: [:show, :edit, :update, :destroy]

    def index
      @users = User.all
    end
  
    def show
    end
  
    def new
      @user = User.new
    end
  
    def edit
    end
  
    def create
      @user = User.new(user_params)
   
      if @user.save
        redirect_to @user
      else
        render 'new'
      end
    end
  
    def update
      @user = User.find(params[:id])
   
      if @user.update(user_params)
        redirect_to @user
      else
        render 'edit'
      end
    end
  
    def destroy
      @user = User.find(params[:id])
      @user.destroy
   
      redirect_to users_url
    end
  
  
    private
  
    def set_user
      @user = User.find(params[:id])
    end

      def user_params
        params.require(:user).permit(:firstname, :lastname, :email , :age)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/catagories_helper.rb
module CatagoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/catagories/_form.html.erb
<%= form_with model: [@user, catagory], local: catagory do |form| %>
    <% if catagory.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(catagory.errors.count, "error") %> prohibited this catagory from being saved:</h2>
  
        <ul>
        <% catagory.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label :Price %>
      <%= form.text_field :price, id: :catagory_price %>
    </div>
  
    <div class="field">
      <%= form.label :Color %>
      <%= form.text_field :color, id: :catagory_color %>
    </div>
  
    <div class="field">
      <%= form.label :Model %>
      <%= form.text_field :model, id: :catagory_model %>
    </div>
  
    <div class="field">
      <%= form.label :Company %>
      <%= form.text_field :company, id: :catagory_company %>
    </div>
  
    <div class="field">
      <%= form.label :city %>
      <%= form.text_field :city, id: :catagory_city %>
    </div>
  
  
  
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>

app/views/catagories/edit.html.erb
<h1>Editing <%= params[:type] %></h1>

<%= render 'form', catagory: @catagory %>
<%= link_to 'Cancel', @user %>

app/views/catagories/new.html.erb
<h1>New <%= params[:type] %></h1>

<%= render 'form', catagory: @catagory %>
<%= link_to 'Cancel', @user %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vehicle</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
    <% if user.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>
  
        <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label :First_name %>
      <%= form.text_field :firstname, id: :user_firstname %>
    </div>
  
    <div class="field">
      <%= form.label :Last_name %>
      <%= form.text_field :lastname, id: :user_lastname %>
    </div>
  
    <div class="field">
      <%= form.label :Email %>
      <%= form.text_field :email, id: :user_email %>
    </div>

    <div class="field">
      <%= form.label :Age %>
      <%= form.text_field :age, id: :user_age %>
    </div>
  
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table class='table'>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.firstname %></td>
        <td><%= user.lastname %></td>
        <td><%= user.email %></td>
        <td><%= user.age %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.firstname %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.lastname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Age:</strong>
  <%= @user.age %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>


<h1>Car Catagory</h1>
<%= link_to 'New', new_user_car_path(@user) %>
<table class='table'>
  <thead>
    <tr>
      <th></th>
      <th>Price</th>
      <th>Color</th>
      <th>Model</th>
      <th>Company</th>
      <th>City</th>
    </tr>
  </thead>
  <tbody>
    <% @user.cars.each do |catagory| %>
      <tr>
        <td><%= link_to 'delete', [@user, catagory], method: :delete %></td>
        <td><%= catagory.price %></td>
        <td><%= catagory.color %></td>
        <td><%= catagory.model %></td>
        <td><%= catagory.company %></td>
        <td><%= catagory.city %></td>
      </tr>    
    <% end %>
  </tbody>
</table>

<h1>Motorcycle Catagory</h1>
<%= link_to 'New', new_user_motorcycle_url(@user) %>
<table class='table'>
  <thead>
    <tr>
    <th></th>
    <th>Price</th>
    <th>Color</th>
    <th>Model</th>
    <th>Company</th>
    <th>City</th>
    </tr>
  </thead>
  <tbody>
  <% @user.motorcycles.each do |catagory| %>
      <tr>
      <td><%= link_to 'delete', [@user, catagory], method: :delete %></td>
      <td><%= catagory.price %></td>
      <td><%= catagory.color %></td>
      <td><%= catagory.model %></td>
      <td><%= catagory.company %></td>
      <td><%= catagory.city %></td>
      </tr>
    <% end %>
  </tbody>
</table>